language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/op/go-logging

notifications:
  email:
    recipients:
      - slok69@gmail.com
    on_success: change
    on_failure: always

script: go test -v ./mydumpster